spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  header: token
  issuer: was
  client-secret: ${JWT_SECRET}
  expiry-seconds: 6000

cloud:
  aws:
    credentials:
#      accessKey:  ${AWS_ACCESS_KEY_ID}
#      secretKey:  ${AWS_SECRET_ACCESS_KEY}
      instanceProfile: true
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
